(ns sandbar.scripts.affordance-map
  "Project the :mm/Verb catalog → a lean, always-resident MCP AFFORDANCE MAP
   (existence-EAGER / detail-LAZY): axis-grouped, one line per verb
   `name — title [safety]`.  Full detail (args + composition edges + WHEN prose)
   is lazy via sandbar.tools.describe; ranked task→verb retrieval via
   sandbar.tools.search.  M9 of the mm/Verb-catalog-maximization arc — the
   resident-existence complement to the on-demand meta-verbs.

   Read-only projection (no writes).  Regenerate whenever the catalog changes.

   Usage: lein run -m sandbar.scripts.affordance-map > <dest>.md"
  (:require [sandbar.db.datatype :as dt]
            [sandbar.db.datomic  :as db]))

(defn- safety
  "Compact safety label from the verb's derived transition-kind."
  [v]
  (case (:mm.verb/transition-kind v)
    :safe       "safe"
    :idempotent "idem"
    :unsafe     "unsafe"
    "?"))

(defn render
  "Render the affordance-map markdown from a seq of :mm/Verb entity-maps."
  [verbs]
  (let [by-axis (into (sorted-map) (group-by #(or (:mm.verb/axis %) :_misc) verbs))
        total   (count verbs)
        sb      (StringBuilder.)]
    (.append sb (format (str "# Sandbar MCP Affordance Map\n\n"
                             "_Generated by `lein affordance-map` from the :mm/Verb catalog — do not hand-edit; regenerate when the catalog changes._\n\n"
                             "%d verbs across %d axes — **existence-eager, detail-lazy**.  "
                             "Rank verbs for a task with `sandbar.tools.search <intent>`; "
                             "get the full card + composition edges (prerequisites / combines-with) "
                             "with `sandbar.tools.describe <verb>`.  "
                             "Safety: `[safe]` read-only · `[idem]` idempotent write · `[unsafe]` mutating.\n\n")
                        total (count by-axis)))
    (doseq [[axis vs] by-axis]
      (.append sb (format "## %s (%d)\n" (name axis) (count vs)))
      (doseq [v (sort-by :mm.verb/name vs)]
        (.append sb (format "- `%s` — %s [%s]\n"
                            (:mm.verb/name v)
                            (or (:mm.verb/title v) "")
                            (safety v))))
      (.append sb "\n"))
    (str sb)))

(defn -main
  "Connect to the configured DB, project the :mm/Verb catalog, print the map."
  [& _]
  (reset! db/**conn* (db/conn (db/db-uri)))
  (let [verbs (dt/all-instances-of :mm/Verb)]
    (print (render verbs))
    (flush)
    (shutdown-agents)
    (System/exit 0)))
