(ns sandbar.scripts.affordance-map
  "Project the verb catalog -> a lean, always-resident MCP AFFORDANCE MAP
   (existence-EAGER / detail-LAZY): axis-grouped, one line per verb
   `name — title [safety]`.  Full detail (args + composition edges + WHEN prose)
   is lazy via sandbar.tools.describe; ranked task->verb retrieval via
   sandbar.tools.search.  M9 of the mm/Verb-catalog-maximization arc — the
   resident-existence complement to the on-demand meta-verbs.

   Read-only projection (no writes).  DB-FREE as of F6: renders from
   `sandbar.mcp.catalog-model/build-catalog-model` (a pure fn of the wire
   `verb-catalog` def), NOT from `:mm/Verb` DB instances.  This closes the
   drift that let the map lag at 81 while the catalog grew to 82 — the count
   line and the row-set now come straight from the single-source model, so a
   stale DB seed can no longer desync the doc.  The drift gate
   (sandbar.scripts.catalog-check) diffs this output against the committed
   doc/mcp-affordance-map.md.

   Usage: lein affordance-map > doc/mcp-affordance-map.md"
  (:require [sandbar.mcp.catalog-model :as model]))

(defn render
  "Render the affordance-map markdown from a catalog-model."
  [m]
  (let [{:keys [verb-count axis-count]} (model/catalog-summary m)
        by-axis (into (sorted-map) (group-by :axis (:verbs m)))
        sb      (StringBuilder.)]
    (.append sb (format (str "# Sandbar MCP Affordance Map\n\n"
                             "_Generated by `lein affordance-map` from the :mm/Verb catalog — do not hand-edit; regenerate when the catalog changes._\n\n"
                             "%d verbs across %d axes — **existence-eager, detail-lazy**.  "
                             "Rank verbs for a task with `sandbar.tools.search <intent>`; "
                             "get the full card + composition edges (prerequisites / combines-with) "
                             "with `sandbar.tools.describe <verb>`.  "
                             "Safety: `[safe]` read-only · `[idem]` idempotent write · `[unsafe]` mutating.\n\n")
                        verb-count axis-count))
    (doseq [[axis vs] by-axis]
      (.append sb (format "## %s (%d)\n" (name axis) (count vs)))
      (doseq [v (sort-by :name vs)]
        (.append sb (format "- `%s` — %s [%s]\n"
                            (:name v)
                            (or (:title v) "")
                            (:safety v))))
      (.append sb "\n"))
    (str sb)))

(defn -main
  "Project the verb catalog (DB-free) and print the affordance map."
  [& _]
  (print (render (model/build-catalog-model)))
  (flush)
  (shutdown-agents)
  (System/exit 0))
