(defn replace-once [s old new] (let [i (.indexOf s old)] (assert (pos? i) (str "not found: " (subs old 0 (min 90 (count old))))) (assert (neg? (.indexOf s old (inc i))) (str "not unique: " (subs old 0 (min 60 (count old))))) (.replace s old new)))
(def S "/private/tmp/claude-501/-Users-dan-claude/737cc1a1-b6da-4e98-9287-4610c850a265/scratchpad/")
;; 1. the namespace
(spit "/Users/dan/src/sandbar/src/sandbar/import.clj" (slurp (str S "import.clj")))
(println "import.clj installed")
;; 2. datatype: the batch primitive with retractions in the same transaction
(def D "/Users/dan/src/sandbar/src/sandbar/db/datatype.clj")
(let [s (slurp D)
      s1 (replace-once s "(declare validate-data)          ;; forward declaration\n"
                       "(defn make-all-with-retractions*\n  \"`make-all*` plus explicit retraction ops in the SAME transaction — the\n   replacement import's per-file unit (REP-03, D7 2026-09-20): the batch\n   firewall floor runs over `entity-specs` (the asserted half, maps with\n   `:dt/type`), and `ops` (`[:db/retract …]` / `[:db.fn/retractEntity …]`\n   vectors the planner derived from the store) transact with them, so a\n   file's re-import replaces its source-owned representation atomically.\n   Firewall-only, like `make-all*`.  Returns the transaction result map.\"\n  [entity-specs ops]\n  (firewall-batch-guard! entity-specs (fw-enforce/index-specs-by-ident entity-specs))\n  (let [result @(d/transact (db/conn) (into (vec ops) entity-specs))]\n    (log/debug :DT/MAKE-ALL-WITH-RETRACTIONS {:entities (count entity-specs) :retractions (count ops)})\n    result))\n\n(declare validate-data)          ;; forward declaration\n")]
  (spit D s1) (println "datatype.clj patched"))
;; 3. db: basis-t for the MCP layer
(def B "/Users/dan/src/sandbar/src/sandbar/db/datomic.clj")
(spit B (str (slurp B) "\n(defn basis-t\n  \"The basis-t of the current database value — the number an import preview\n   reports and a persist pins with `expect-basis` (D7, 2026-09-20).\"\n  []\n  (d/basis-t (db)))\n"))
(println "datomic.clj patched")
;; 4. projection: the source hash on every unit
(def P "/Users/dan/src/sandbar/src/sandbar/projection.clj")
(let [s (slurp P)
      s1 (-> s
             (replace-once "(defn- parse-unit\n" "(defn- sha256-hex\n  \"The SHA-256 of `text` as lowercase hex — the source fingerprint a unit\n   carries so a preview and its apply can be told apart (D7, 2026-09-20).\"\n  [^String text]\n  (let [md (java.security.MessageDigest/getInstance \"SHA-256\")]\n    (apply str (map #(format \"%02x\" %) (.digest md (.getBytes text \"UTF-8\"))))))\n\n(defn- parse-unit\n")
             (replace-once "    (let [[parsed error] (try\n                           [(vec (md/parse-document (slurp file) source)) nil]\n"
                           "    (let [text (slurp file)\n          sha  (sha256-hex text)\n          [parsed error] (try\n                           [(vec (md/parse-document text source)) nil]\n")
             (replace-once "      (if error\n        {:source source :status :parse-failed :entities [] :error error}\n"
                           "      (if error\n        {:source source :status :parse-failed :entities [] :error error :source-sha256 sha}\n")
             (replace-once "          {:source       source\n           :status       (if (and (seq parsed) (empty? kept)) :filtered :parsed)\n           :entities     (vec kept)\n"
                           "          {:source       source\n           :source-sha256 sha\n           :status       (if (and (seq parsed) (empty? kept)) :filtered :parsed)\n           :entities     (vec kept)\n"))]
  (spit P s1) (println "projection.clj patched"))
;; 5. tools: the handler plans each unit, refuses conflicts, pins the basis; the card
(def T "/Users/dan/src/sandbar/src/sandbar/mcp/tools.clj")
(let [s (slurp T)
      s1 (-> s
             (replace-once "            [sandbar.projection      :as pg]\n" "            [sandbar.import          :as import]\n            [sandbar.projection      :as pg]\n")
             (replace-once "  (cond-> {:source (:source unit) :status (:status unit)}\n    (:class unit)              (assoc :dt/type (:class unit) :ident (:ident unit))\n"
                           "  (cond-> {:source (:source unit) :status (:status unit)}\n    (:source-sha256 unit)      (assoc :source-sha256 (:source-sha256 unit))\n    (:class unit)              (assoc :dt/type (:class unit) :ident (:ident unit))\n")
             (replace-once "        persist?    (boolean (or (get args \"persist?\")\n                                  (get args \"persist\")\n                                  (get args :persist?)\n                                  (get args :persist)))]\n    (when-not from\n      (throw (ex-info \"project.import requires :from (input directory path)\"\n                      {:args args})))\n"
                           "        persist?    (boolean (or (get args \"persist?\")\n                                  (get args \"persist\")\n                                  (get args :persist?)\n                                  (get args :persist)))\n        ;; REP-03 (D7, 2026-09-20): a file the substrate already holds is\n        ;; REPLACED — its source-owned representation, sections and carrier\n        ;; reconciled in one transaction — unless `mode` is `additive`.\n        mode        (let [m (or (get args \"mode\") (get args :mode))]\n                      (if (= \"additive\" (some-> m name)) :additive :replace))\n        expect-basis (or (get args \"expect-basis\") (get args :expect-basis))]\n    (when-not from\n      (throw (ex-info \"project.import requires :from (input directory path)\"\n                      {:args args})))\n    (when (and persist? expect-basis (not= (long expect-basis) (db/basis-t)))\n      (throw (ex-info (str \"project.import: the database moved since the preview (expected basis \"\n                           expect-basis \", now \" (db/basis-t) \"); preview again\")\n                      {:reasons #{:import/basis-moved} :expected expect-basis :actual (db/basis-t)})))\n")
             ;; the dry run plans every unit and reports it
             (replace-once "            (merge {:from     from\n                    :filter   filter-spec\n                    :persist? false\n                    :entities (mapv (fn [e]\n                                      {:dt/type (:dt/type e)\n                                       :ident   (:db/ident e)})\n                                    entities)}\n                   accounting))\n"
                           "            (let [db-now  (db/db)\n                  planned (mapv (fn [u]\n                                  (let [p (import/plan-unit db-now (:entities u) {:mode mode})]\n                                    (cond-> (assoc (import-unit-summary u) :mode (:mode p))\n                                      (= :replace (:mode p)) (assoc :retracted-sections (:retracted-sections p)\n                                                                   :retracted-slots (:retracted-slots p)\n                                                                   :retracted-carrier? (:retracted-carrier? p))\n                                      (seq (:conflicts p)) (assoc :conflicts (:conflicts p)))))\n                                parsed)]\n              (merge {:from     from\n                     :filter   filter-spec\n                     :persist? false\n                     :mode     mode\n                     :basis    (db/basis-t)\n                     :units    planned\n                     :conflict-count (count (filter :conflicts planned))\n                     :entities (mapv (fn [e]\n                                       {:dt/type (:dt/type e)\n                                        :ident   (:db/ident e)})\n                                     entities)}\n                    accounting)))\n")
             ;; the persist plans each unit, refuses conflicts, applies the rest
             (replace-once "                         (let [group   (:entities unit)\n                               rec     {:dt/type     (:class unit)\n                                        :ident       (:ident unit)\n                                        :source      (:source unit)\n                                        :tx-entities (count group)}\n                               ;; Bug fix 2026-05-21: do NOT dissoc :dt/type\n                               ;; before transact.  Without :dt/type the entity\n                               ;; has no class, and class.instances / aggregate.count\n                               ;; can't find it.\n                               tx-data (codec-md/entity-specs->tx-data group)]\n                           (try\n                             (dt/make-all* tx-data)\n                             (update acc :persisted conj rec)\n"
                           "                         (let [group   (:entities unit)\n                               plan    (import/plan-unit (db/db) group {:mode mode})\n                               rec     (cond-> {:dt/type     (:class unit)\n                                                :ident       (:ident unit)\n                                                :source      (:source unit)\n                                                :source-sha256 (:source-sha256 unit)\n                                                :mode        (:mode plan)\n                                                :tx-entities (count group)}\n                                         (= :replace (:mode plan))\n                                         (assoc :retracted-sections (:retracted-sections plan)\n                                                :retracted-slots (:retracted-slots plan)\n                                                :retracted-carrier? (:retracted-carrier? plan)))]\n                           (try\n                             (if (seq (:conflicts plan))\n                               (do (log/warn :IMPORT/UNIT-CONFLICT {:idx idx :source (:source unit) :conflicts (:conflicts plan)})\n                                   (update acc :conflicts conj (assoc rec :conflicts (:conflicts plan))))\n                               (do (import/apply-plan! plan)\n                                   (update acc :persisted conj rec)))\n")
             (replace-once "                       {:persisted [] :failed [] :refused []}\n                       (map-indexed vector parsed))\n"
                           "                       {:persisted [] :failed [] :refused [] :conflicts []}\n                       (map-indexed vector parsed))\n")
             (replace-once "              totals  {:attempted    (count units)\n                       :persisted    (count (:persisted results))\n                       :failed       (count (:failed results))\n                       :refused      (count (:refused results))\n                       :parse-failed (count parse-failed)\n                       :skipped      skipped}\n              reconciled? (= (:attempted totals)\n                             (+ (:persisted totals) (:failed totals) (:refused totals)\n                                (:parse-failed totals) (:skipped totals)))]\n"
                           "              totals  {:attempted    (count units)\n                       :persisted    (count (:persisted results))\n                       :failed       (count (:failed results))\n                       :refused      (count (:refused results))\n                       :conflicts    (count (:conflicts results))\n                       :parse-failed (count parse-failed)\n                       :skipped      skipped}\n              reconciled? (= (:attempted totals)\n                             (+ (:persisted totals) (:failed totals) (:refused totals) (:conflicts totals)\n                                (:parse-failed totals) (:skipped totals)))]\n")
             (replace-once "          (merge {:from            from\n                  :filter          filter-spec\n                  :persist?        true\n                  ;; one transaction unit per parsed file\n                  :groups          total\n                  :persisted-count (count (:persisted results))\n"
                           "          (merge {:from            from\n                  :filter          filter-spec\n                  :persist?        true\n                  :mode            mode\n                  :basis           (db/basis-t)\n                  ;; one transaction unit per parsed file\n                  :groups          total\n                  :persisted       (:persisted results)\n                  :persisted-count (count (:persisted results))\n                  ;; REP-03: a unit refused for ambiguity (a class change, an\n                  ;; identity conflict, a section another record references)\n                  :conflict-count  (count (:conflicts results))\n                  :conflicts       (:conflicts results)\n")
             ;; the card
             (replace-once "`:persist` (optional, default false) — WITHOUT it the verb is a DRY RUN: it parses and reports but transacts nothing.  ACCOUNTING (D6, 2026-09-19)"
                           "`:persist` (optional, default false) — WITHOUT it the verb is a DRY RUN: it parses, PLANS every unit and reports, but transacts nothing.  REPLACEMENT (D6/D7, 2026-09-20): a file the substrate already holds is REPLACED — the file's declared slots win, an omitted source-owned slot is retracted, a cardinality-many slot is set-replaced, sections the file no longer carries are retracted with their links, the carrier is replaced or retracted — in ONE transaction per file, while the host's identity, the refs into it, and the facts the substrate or another owner maintains (created, last-touched, created-by, owning-project, visibility, the id) are kept; `:mode` `additive` opts into the pre-D7 additive behaviour.  A unit is REFUSED as a conflict, never guessed, when the file's class differs from the stored one, its `id:` differs from the stored `mm/id`, or a section it drops is referenced by a record outside the document (`:conflicts`, with the reason).  `:expect-basis` (optional) pins a persist to the basis a preview reported: if the database moved, the call is refused and the preview must be repeated; every unit reports its `:source-sha256`.  ACCOUNTING (D6, 2026-09-19)")
             (replace-once "(files whose front matter carried keys the class does not declare), and `:skipped-count` (files the filter excluded, or that could not match the tree filter).  With `:persist` the response adds `:persisted-count`,"
                           "(files whose front matter carried keys the class does not declare), and `:skipped-count` (files the filter excluded, or that could not match the tree filter); a dry run adds `:units` (each file's planned `:mode` — `insert`, `replace` or `additive` — with the retractions a replace would make and any `:conflicts`) and `:basis`.  With `:persist` the response adds `:persisted-count` and `:persisted` (each unit's mode and retraction counts),")
             (replace-once "`:refused-count` + `:refused [...]` (a unit the import firewall refused — a governed edge the floor forbade), `:groups` (the transaction units), and `:totals` + `:reconciled?` — attempted = persisted + failed + refused + parse-failed + skipped."
                           "`:refused-count` + `:refused [...]` (a unit the import firewall refused — a governed edge the floor forbade), `:conflict-count` + `:conflicts [...]` (a unit refused for ambiguity under replacement), `:groups` (the transaction units), and `:totals` + `:reconciled?` — attempted = persisted + failed + refused + conflicts + parse-failed + skipped.")
             (replace-once "                    :persist  {:type        \"boolean\"\n                               :description \"When true, transact each parsed source unit (ONE transaction per file) into the substrate."
                           "                    :mode     {:type \"string\" :description \"'replace' (default): a file the substrate already holds replaces its source-owned representation in one transaction; 'additive': the pre-D7 behaviour, assertions only (for ingestion from independent sources).\"}\n                    :expect-basis {:type \"number\" :description \"Pin a persist to the :basis a dry run reported; refused if the database moved since (preview again).\"}\n                    :persist  {:type        \"boolean\"\n                               :description \"When true, transact each parsed source unit (ONE transaction per file) into the substrate."))]
  (spit T s1) (println "tools.clj patched"))
